DROP TABLE IF EXISTS compilations_events, compilations, requests, events, categories, users;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(264) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    annotation TEXT NOT NULL,
    category_id BIGINT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    initiator_id BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit BIGINT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(50),
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_events_user FOREIGN KEY (initiator_id) REFERENCES users (id) ON delete CASCADE,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(50),
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request_user FOREIGN KEY (requester_id) REFERENCES users (id) ON delete CASCADE,
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   pinned BOOLEAN,
   title VARCHAR(50),
   CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT NOT NULL ,
    event_id BIGINT NOT NULL ,
    CONSTRAINT pk_comp_events PRIMARY KEY (compilation_id, event_id) ,
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON delete CASCADE ,
    CONSTRAINT fk_events FOREIGN KEY (event_id) REFERENCES events (id) ON delete CASCADE
);
